# Generated by Django 4.2.7 on 2024-01-03 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_sex_product_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
