# Generated by Django 4.2.7 on 2024-01-14 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_cartitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='price',
        ),
    ]
