# Generated by Django 4.2.7 on 2024-01-14 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_cartitem_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='total_price',
        ),
    ]
